---

- name: Install Update CRON
  template:
    src="ubuntu-mirror.j2"
    dest="{{ mirror_cron_dir }}/ubuntu-mirror"
    owner="{{ mirror_unix_user }}"
    group="{{ mirror_unix_group }}"
    mode=0700

- name: Setup CRON Schedule
  cron:
    name="Ubuntu"
    minute="{{ 59 | random(seed=inventory_hostname) }}"
    hour="{{ 23 | random(seed=inventory_hostname) }}"
    user="{{ mirror_unix_user }}"
    state="present"
    job="{{ mirror_cron_dir }}/ubuntu-mirror"
    disabled="{{ ubuntu_mirror_cron_disabled }}"
