---

- name: Install Update CRON
  template:
    src="ubuntu-mirror.j2"
    dest="{{ mirror_cron_dir }}/ubuntu-mirror"
    owner="{{ mirror_unix_user }}"
    group="{{ mirror_unix_group }}"
    mode=0700

- name: Setup CRON Schedule
  cron:
    name="Ubuntu"
    minute="{{ ubuntu_mirror_cron_minute }}"
    hour="{{ ubuntu_mirror_cron_hour }}"
    user="{{ mirror_unix_user }}"
    state="present"
    job="{{ mirror_cron_dir }}/ubuntu-mirror >/dev/null 2>&1"
    disabled="{{ ubuntu_mirror_cron_disabled }}"

- stat:
    path="{{ mirror_timestamp_dir }}/ubuntu"
  register: tsfile

- name: Seed Timestamp File
  copy:
    content="0"
    dest="{{ mirror_timestamp_dir }}/ubuntu"
    owner="{{ mirror_unix_user }}"
    group="{{ mirror_unix_group }}"
    mode=0644
  when: not tsfile.stat.exists

- stat:
    path="{{ mirror_timestamp_dir }}/ubuntu-releases"
  register: tsfile

- name: Seed Timestamp File
  copy:
    content="0"
    dest="{{ mirror_timestamp_dir }}/ubuntu-releases"
    owner="{{ mirror_unix_user }}"
    group="{{ mirror_unix_group }}"
    mode=0644
  when: not tsfile.stat.exists
